name: "ubuntu bash hypervisor fuzzing CI workflow"


on:
  push:
    branches: [ main ]
  schedule:
      - cron:  '0 0 1 * *' ##execution of a task in the first minute of the month  

jobs:

  ubuntu-latest-kafl-job:
    name: "kafl on ubuntu-latest"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status    
    - name: "deploy kafl"
      run: sudo make deploy-kafl

  ubuntu-latest-kfx-job:
    name: "kfx on ubuntu-latest"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status    
    - name: "deploy kfx"
      run: sudo make deploy-kfx